-- Computed UNSW-NB15 (original) features table
-- Note: some features are dummy values due to
-- being too expensive to compute in real-time
CREATE TABLE IF NOT EXISTS og_features (
    srcip VARCHAR,
    sport BIGINT,
    dstip VARCHAR,
    dsport BIGINT,
    proto VARCHAR,
    state VARCHAR,
    dur DOUBLE,
    sbytes BIGINT,
    dbytes BIGINT,
    sttl BIGINT,
    dttl BIGINT,
    sloss BIGINT,
    service VARCHAR,
    sload DOUBLE,
    dload DOUBLE,
    spkt BIGINT,
    dpkt BIGINT,
    swin BIGINT,
    dwin BIGINT,
    stcpb BIGINT,
    dtcpb BIGINT,
    smeanz BIGINT,
    dmeanz BIGINT,
    trans_depth BIGINT,
    resp_bdy_len BIGINT,
    sjit DOUBLE,
    djit DOUBLE,
    stime DOUBLE,
    ltime DOUBLE,
    sinpkt DOUBLE,
    dinpkt DOUBLE,
    tcprtt DOUBLE,
    synack DOUBLE,
    ackdat DOUBLE,
    is_sm_ips_ports BOOLEAN,
    ct_state_ttl BIGINT,
    ct_flw_http_methd BIGINT,
    is_ftp_login BOOLEAN,
    ct_ftp_cmd BIGINT,
    ct_srv_src BIGINT,
    ct_srv_dst BIGINT,
    ct_dst_ltm BIGINT,
    ct_src_ltm BIGINT,
    ct_src_dport_ltm BIGINT,
    ct_dst_sport_ltm BIGINT,
    ct_dst_src_ltm BIGINT,
)
