-- Computed NF-UNSW-NB15 (NetFlow version) features table
CREATE TABLE IF NOT EXISTS nf_features (
    uid VARCHAR PRIMARY KEY,
    ts DOUBLE,  -- Flow start timestamp (same as flow_start_milliseconds)
    ipv4_src_addr VARCHAR,
    l4_src_port BIGINT,
    ipv4_dst_addr VARCHAR,
    l4_dst_port BIGINT,
    protocol VARCHAR,
    l7_proto VARCHAR,
    in_bytes BIGINT,
    out_bytes BIGINT,
    in_pkts BIGINT,
    out_pkts BIGINT,
    flow_duration_milliseconds DOUBLE,
    tcp_flags BIGINT,
    client_tcp_flags BIGINT,
    server_tcp_flags BIGINT,
    duration_in DOUBLE,
    duration_out DOUBLE,
    min_ttl BIGINT,
    max_ttl BIGINT,
    logest_flow_pkt BIGINT,
    shortest_flow_pkt BIGINT,
    min_ip_pkt_len BIGINT,
    max_ip_pkt_len BIGINT,
    src_to_dst_second_bytes DOUBLE,
    dst_to_src_second_bytes DOUBLE,
    retransmitted_in_bytes BIGINT,
    retransmitted_out_bytes BIGINT,
    retransmitted_in_pkts BIGINT,
    retransmitted_out_pkts BIGINT,
    src_to_dst_avg_throughput DOUBLE,
    dst_to_src_avg_throughput DOUBLE,
    num_pkts_up_to_128_bytes BIGINT,
    num_pkts_128_to_256_bytes BIGINT,
    num_pkts_256_to_512_bytes BIGINT,
    num_pkts_512_to_1024_bytes BIGINT,
    num_pkts_1024_to_1514_bytes BIGINT,
    tcp_win_max_in BIGINT,
    tcp_win_max_out BIGINT,
    icmp_type BIGINT,
    icmp_ipv4_type BIGINT,
    dns_query_id BIGINT,
    dns_query_type BIGINT,
    dns_ttl_answer BIGINT,
    ftp_command_ret_code BIGINT,
    flow_start_milliseconds DOUBLE,
    flow_end_milliseconds DOUBLE,
    src_to_dst_iat_min DOUBLE,
    src_to_dst_iat_max DOUBLE,
    src_to_dst_iat_avg DOUBLE,
    src_to_dst_iat_stddev DOUBLE,
    dst_to_src_iat_min DOUBLE,
    dst_to_src_iat_max DOUBLE,
    dst_to_src_iat_avg DOUBLE,
    dst_to_src_iat_stddev DOUBLE,
    computed_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
)
